### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Tuvqlu** [vecnavium-pm-pl/VecnaLeaderboards#58]
Hi there are a few bugs I need to report

1. Kill streak leaderboard doesn't work

2. Levels leaderboard crashes

Version: 2.1.6

Thanks!

**Comment by Tuvqlu** [comment]
Also, leaderboards do not work in worlds that are not spawn

**Comment by Vecnavium** [comment]
> Also, leaderboards do not work in worlds that are not spawn

This issue isn't a plugin issue exactly. If you do not have a plugin or some sort that loads all of your worlds automatically VecnaLeaderboards will not function at all. I have fixed one issue which is linked to [this commit](https://github.com/vecnavium-pm-pl/VecnaLeaderboards/commit/5c19966b3a6851669cd565ee9ee088b53289ca5d) but now if this issue occurs again it's because of the world not being loaded which you must have it loaded automatically for VecnaLeaderboards to work

**Comment by Vecnavium** [comment]
The issue for Kill Streak leaderboard is still an ongoing issue
The levels leaderboard and level system overall has been fixed and is now working as expected.

**Comment by Vecnavium** [comment]
KillStreaks leaderboard has been removed due to the amount of complications of attempting to fix it. It might be added later on again with it fully functioning.
